include: package:lint/package.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
linter:
  rules:
    avoid_dynamic_calls: true
    prefer_final_locals: true
    no_leading_underscores_for_local_identifiers: false
    require_trailing_commas: true
    curly_braces_in_flow_control_structures: false
    unawaited_futures: true
    prefer_single_quotes: true
    sort_pub_dependencies: false
analyzer: 
  errors:
    avoid_bool_literals_in_conditional_expressions: ignore
    avoid_dynamic_calls: ignore
    avoid_print: ignore
    cast_nullable_to_non_nullable: warning
    prefer_single_quotes: ignore ignore ignore warning
    require_trailing_commas: warning
    sdk_version_since: ignore
    strict_raw_type: ignore
    unrelated_type_equality_checks: warning
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true